# =============================================================================
# PURPOSE
# This script builds your first LangGraph application — an invoice review
# workflow with three nodes and a conditional routing function. It connects
# to Azure OpenAI to generate human-readable approval and review notes.
# This is the structural template for every agent and pipeline you will build
# from Day 2 onward. The same pattern of state, nodes, edges, and routing
# is used in rag_pipeline.py and in the multi-agent system on Day 4.
# =============================================================================


# --- Standard Python libraries ---
# os: reads environment variables (API key, endpoint) from the .env file
import os

# TypedDict: lets us define the State as a typed dictionary
# This tells Python exactly what keys the state can contain and their types
from typing import TypedDict

# --- Third-party libraries ---
# load_dotenv: reads your .env file and loads AZURE_* variables into memory
from dotenv import load_dotenv

# StateGraph: the main LangGraph class used to build and compile a graph
# END: a special marker that tells LangGraph the workflow has finished
from langgraph.graph import StateGraph, END

# AzureChatOpenAI: connects LangGraph to your Azure OpenAI GPT-4o deployment
# Used here to generate approval notes and review request messages
from langchain_openai import AzureChatOpenAI


# --- Load credentials from .env file into environment ---
load_dotenv()


# =============================================================================
# STEP 1 — DEFINE THE STATE
# State is the shared notepad that every node in this graph reads and writes.
# Think of it as a whiteboard visible to all three nodes simultaneously.
# Every key you define here is a field that nodes can read from or update.
# =============================================================================
class InvoiceReviewState(TypedDict):
    # The unique invoice reference number
    invoice_id:   str

    # The name of the vendor who issued the invoice
    vendor:       str

    # The total monetary value of the invoice
    total:        float

    # How confident the extraction model was (0.0 to 1.0)
    # This drives the routing decision — below 0.85 triggers human review
    confidence:   float

    # The outcome of the workflow: "pending", "approved", or "review_required"
    decision:     str

    # Plain-English reason why the invoice was flagged (if applicable)
    reason:       str

    # The approval note or review request note generated by GPT-4o
    review_notes: str


# =============================================================================
# STEP 2 — INITIALISE AZURE OPENAI
# This creates one shared LLM connection used by both node functions below.
# temperature=0 means the model gives consistent, factual responses
# rather than creative or variable ones — important for business documents.
# =============================================================================
llm = AzureChatOpenAI(
    azure_deployment=os.getenv("AZURE_OPENAI_DEPLOYMENT"),  # e.g. "gpt-4o"
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),      # your resource URL
    api_key=os.getenv("AZURE_OPENAI_KEY"),                  # your API key
    api_version=os.getenv("AZURE_OPENAI_API_VERSION"),      # e.g. "2024-08-01-preview"
    temperature=0                                            # consistent outputs
)


# =============================================================================
# STEP 3 — DEFINE NODES
# Each node is a Python function that:
#   - Receives the full current state as its input
#   - Does one specific job
#   - Returns a dictionary of ONLY the keys it wants to update in the state
# Nodes never replace the entire state — they only update what they touched.
# =============================================================================

def validate_extraction(state: InvoiceReviewState) -> dict:
    """
    Node 1 — Validation Gate.
    Reads the confidence score and total amount from the state.
    Sets the initial decision to "pending" and writes the reason for review
    if one applies. Does NOT call GPT-4o — this is pure business logic.
    """
    print(f"[validate_extraction] Invoice: {state['invoice_id']}  Confidence: {state['confidence']:.0%}")

    # Check both conditions that would require human review
    # Condition 1: extraction confidence too low (model was not sure)
    # Condition 2: invoice value too high (needs senior approval)
    return {
        "decision": "pending",
        # Write the reason so the next node knows why it was flagged
        "reason": "High value invoice requires review" if state["total"] > 50000
                   else ("Low confidence" if state["confidence"] < 0.85 else ""),
    }


def auto_approve(state: InvoiceReviewState) -> dict:
    """
    Node 2a — Auto Approval.
    Only reached if confidence is high AND total is within the threshold.
    Calls GPT-4o to generate a one-sentence professional approval note.
    Writes "approved" to the decision field and saves the generated note.
    """
    print(f"[auto_approve] Approving invoice {state['invoice_id']} for {state['vendor']}")

    # Build the prompt using invoice details from the state
    prompt = (
        f"You are an accounts payable assistant. Write a one-sentence approval note "
        f"for invoice {state['invoice_id']} from {state['vendor']} "
        f"for the amount of ${state['total']:,.2f}."
    )

    # Call GPT-4o — note.content contains the generated text
    note = llm.invoke(prompt)

    # Return only the two fields this node is responsible for updating
    return {"decision": "approved", "review_notes": note.content}


def flag_for_review(state: InvoiceReviewState) -> dict:
    """
    Node 2b — Human Review Flag.
    Reached when confidence is low OR total exceeds the threshold.
    Calls GPT-4o to generate a review request note explaining why.
    Writes "review_required" to the decision field.
    """
    print(f"[flag_for_review] Flagging invoice {state['invoice_id']} - Reason: {state['reason']}")

    # Build the prompt — include the reason so GPT-4o explains it clearly
    prompt = (
        f"You are an accounts payable assistant. Write a brief review request note "
        f"for invoice {state['invoice_id']} from {state['vendor']} "
        f"for ${state['total']:,.2f}. Reason for review: {state['reason']}."
    )

    note = llm.invoke(prompt)

    return {"decision": "review_required", "review_notes": note.content}


# =============================================================================
# STEP 4 — DEFINE THE ROUTING FUNCTION
# This is the conditional edge logic. It reads the state after the validate
# node runs and returns a STRING naming the next node to execute.
# LangGraph uses that string to follow the correct edge automatically.
# This function is never called directly — LangGraph calls it internally.
# =============================================================================
def route_invoice(state: InvoiceReviewState) -> str:
    """
    Conditional router — runs after the validate node completes.
    Returns "auto_approve" if both quality conditions are met.
    Returns "flag_for_review" if either condition fails.
    The returned string must exactly match a node name added to the graph.
    """
    if state["confidence"] >= 0.85 and state["total"] <= 50000:
        return "auto_approve"     # route to auto approval node
    return "flag_for_review"      # route to human review node


# =============================================================================
# STEP 5 — BUILD AND COMPILE THE GRAPH
# This is where you wire everything together:
#   add_node()               registers each function as a named node
#   set_entry_point()        defines which node runs first
#   add_conditional_edges()  attaches the routing function to a node
#   add_edge()               creates a direct connection (no condition)
#   compile()                locks the graph and returns a runnable app
# Nothing runs yet — compile() just validates and prepares the graph.
# =============================================================================
graph = StateGraph(InvoiceReviewState)

# Register all three node functions with their names
graph.add_node("validate",        validate_extraction)
graph.add_node("auto_approve",    auto_approve)
graph.add_node("flag_for_review", flag_for_review)

# The graph always starts at the validate node
graph.set_entry_point("validate")

# After validate, call route_invoice() to decide which node runs next
# route_invoice returns either "auto_approve" or "flag_for_review"
graph.add_conditional_edges("validate", route_invoice)

# After either outcome node, the workflow ends
graph.add_edge("auto_approve",    END)
graph.add_edge("flag_for_review", END)

# Compile the graph into a runnable application
# app.invoke() is how you run the workflow on a single invoice
app = graph.compile()


# =============================================================================
# STEP 6 — TEST WITH SAMPLE INVOICES
# Runs only when you execute this script directly.
# Each invoice dict matches the InvoiceReviewState structure exactly.
# app.invoke() runs the full graph and returns the final state.
# =============================================================================
if __name__ == "__main__":

    # Three test invoices covering all three routing scenarios:
    # INV-001: high confidence + low value  → auto_approve
    # INV-002: high confidence + HIGH value → flag_for_review (value rule)
    # INV-003: LOW confidence + low value   → flag_for_review (confidence rule)
    test_invoices = [
        {"invoice_id": "INV-001", "vendor": "Contoso Consulting", "total": 12500.00, "confidence": 0.92, "decision": "", "reason": "", "review_notes": ""},
        {"invoice_id": "INV-002", "vendor": "Acme Corp",          "total": 75000.00, "confidence": 0.95, "decision": "", "reason": "", "review_notes": ""},
        {"invoice_id": "INV-003", "vendor": "Unknown Vendor",     "total": 8000.00,  "confidence": 0.71, "decision": "", "reason": "", "review_notes": ""},
    ]

    print("=== Invoice Review Workflow ===")

    for invoice in test_invoices:
        print(f"\nProcessing: {invoice['invoice_id']}")

        # Run the full graph — returns the final state after all nodes complete
        result = app.invoke(invoice)

        # Print the two fields written by the final node
        print(f"  Decision : {result['decision']}")
        print(f"  Notes    : {result['review_notes']}")


# =============================================================================
# SCRIPT SUMMARY
# =============================================================================
#
# WHAT THIS SCRIPT DOES
# Builds a three-node LangGraph invoice review workflow. Validates each invoice
# against confidence and value thresholds, routes to auto-approval or human
# review accordingly, and generates GPT-4o written notes for each outcome.
#
# HOW IT WORKS — STEP BY STEP
# 1. State defined        — shared notepad with 7 fields all nodes can read/write
# 2. LLM initialised      — one Azure OpenAI connection shared by both action nodes
# 3. validate node        — checks confidence and total, sets decision to pending
# 4. route_invoice()      — reads state, returns name of next node as a string
# 5. auto_approve node    — generates approval note via GPT-4o
# 6. flag_for_review node — generates review request note via GPT-4o
# 7. graph compiled       — wired together and locked into a runnable app
# 8. app.invoke()         — runs the full graph for each test invoice
#
# ROUTING LOGIC
# confidence >= 0.85 AND total <= 50000  →  auto_approve
# confidence <  0.85 OR  total >  50000  →  flag_for_review
#
# WHERE THIS IS USED NEXT
# Day 2 Lab 2.3 : the same node-edge-route pattern is used in rag_pipeline.py
# Day 3         : this file is extended with memory and tool-calling nodes
# Day 4         : this graph becomes one specialist agent under a supervisor
# Day 5         : the decision and review_notes fields become the audit trail
#
# COMMON ERRORS AND FIXES
# AuthenticationError      → AZURE_OPENAI_KEY is wrong, re-copy from portal
# DeploymentNotFoundError  → AZURE_OPENAI_DEPLOYMENT does not match Studio name
# RateLimitError           → wait 60 seconds, then retry
# ModuleNotFoundError      → run: pip install langgraph langchain-openai
# =============================================================================
